#!/bin/sh
{% set fs_op  = self._TemplateReference__context.name %}
set -e
export DIR_NAME=$1

CACHE_NAME="/tmp/cache_`echo ${DIR_NAME} | md5sum - | cut -f1 -d' '`"
#if [ -f "${CACHE_NAME}" ]; then
#  cat ${CACHE_NAME}
#  echo ${DIR_NAME} use cache ${CACHE_NAME} >> /tmp/aws_log
#  exit 0
#fi

echo {{ fs_op }} $DIR_NAME >> /tmp/aws_debug


{% macro tree(parent_path, fs, parent_fs) %}

  {% if fs is mapping and parent_fs is not none %}
    {% set dummy=fs.__setitem__("__parent", parent_fs) %}
  {% endif %}

  {% for path in fs %}
    {# skip virtual parent ref #}
    {% if path == "__parent" %}
      {% continue %} 
    {% endif %} {# if path == "__parent" #}
    {% if path != fs_op and path[:1] == "/" %} 
      {{ tree(parent_path + "/" + path if (parent_path != "/") else path, fs[path], fs) }} 
      {% continue %}
    {% endif %} {# if path != fs_op #}
  {% endfor %}
  if (path ~ /^{{ parent_path | regex_replace("//", "/", "g") | regex_replace("/", "\/", "g") }}$/) {
  {% if fs_op in fs %}
    {# set context #} 
    path_lvl=NF-1
    {% if fs["__parent"] is mapping and "name" in fs['__parent'] %}
    printf("echo export \"%s\"=\"%s\"\n", "{{ fs['__parent'].name }}", $path_lvl)
    path_lvl=path_lvl-1  
    {% endif %}


    {% set dir = fs[fs_op] %}
    {% if "cmd" in dir %}
      {% set cmd = dir["cmd"] | join(" |") %}
      {% set parser = dir["parser"] | join(" |") %}
      {% set cmd = "( " + cmd + " )" %} 
      {% set parser = "( " + parser + " )" %} 
      printf("echo {{ ( cmd + " | " + parser ) | b64encode }} | base64 -d\n")
    {% endif %} {# if "cmd" in dir #}
  {% endif %} {# if fs_op in fs #}
  } 
{%- endmacro %}

echo ${DIR_NAME} | awk -F/ '
BEGIN {
  printf("export LVL1=\"/\"\n")
  for (i = 2; i <= NF; i++) {
    printf("export LVL%d=\"%s\"\n", i, $i)
  } 
} 
{
  path=$0

{{ tree("/", fs, none) }}

}' | sh - | tee /tmp/aws_debug.txt | (sh - | tee /tmp/cache_`echo ${DIR_NAME} | md5sum - | cut -f1 -d" "`)
