#!/bin/sh
{% set fs_op  = self._TemplateReference__context.name %}
set -e
DIR_NAME=$1

{% macro readdir(parent, fs) %}
  {% for path in fs %}
    {% if path != fs_op %} 
      {{ readdir(parent + "/" + path if (parent != "/") else path, fs[path]) }} 
    {% endif %} {# if path != fs_op #}
  {% endfor %}
  if (path ~ /^{{ parent | regex_replace("/", "\/", "g") }}$/) {
  {% if fs_op in fs %}
    {% set dir = fs[fs_op] %}
    {% if "cmd" in dir %}
      printf("export LVL1=\"/\"\n")
      for (i = 2; i <= NF; i++) {
        printf("export LVL%d=\"%s\"\n", i, $i)
      } 
      {% set cmd = dir["cmd"] | join(" |") %}
      {% set parser = dir["parser"] | join(" |") %}
      
      {% set cmd = "( " + cmd + " )" %} 
      {% set parser = "( " + parser + " )" %} 
      printf("echo {{ ( cmd + " | " + parser ) | b64encode }} | base64 -d\n")
    {% endif %} {# if "cmd" in dir #}
  {% endif %} {# if fs_op in fs #}
  } 
{%- endmacro %}

echo ${DIR_NAME} | awk -F/ '{
  path=$0

{{ readdir("/", fs) }}

}' | sh - | sh -
