#!/bin/sh
#echo 'ino=1 mode=drwxr-xr-x nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
if [ "$1" = "/" ]; then
    echo 'ino=1 mode=drwxrwxrwx nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
  else
    if [ "$1" = "/ctl" ]; then
      echo 'ino=1 mode=-rw-rw-rw- nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
    fi
    if [ "$1" = "/result" ]; then
      echo 'ino=1 mode=-r--r--r-- nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
    fi
fi
