#!/bin/sh

if [ "$1" = "/" ]; then
    echo 'ino=1 mode=drwxr-xr-x nlink=1 uid=0 gid=0 rdev=0 size=1224 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
fi
if [ "$1" = "/ctl" ]; then
    echo 'ino=1 mode=--w--w--w- nlink=1 uid=0 gid=0 rdev=0 size=1111 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
fi

if [ "$1" = "/result" ]; then
    echo 'ino=1 mode=-r--r--r-- nlink=1 uid=0 gid=0 rdev=0 size=176 blksize=512 blocks=2 atime=0 mtime=0 ctime=0 '
fi
